name: Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore test/Neptuo.Productivity.SnippetManager.Tests/
      
    - name: Build
      run: dotnet build test/Neptuo.Productivity.SnippetManager.Tests/ --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test test/Neptuo.Productivity.SnippetManager.Tests/ --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/TestResults/*.xml
          **/TestResults/*.trx
          
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-reports
        path: |
          **/TestResults/**/coverage.cobertura.xml